### ISSUE TITLE
"translations" field and arbitrary setting

### ISSUE THREAD

**Issue by Grafikart** [vinkla/extended-acf#115]
When translation is enabled on Wordpress the field get a new setting that handle translation 

![image](https://user-images.githubusercontent.com/395137/203383645-7ea58cf3-a696-44d7-8d10-4801c357858b.png)

I would like to be able to set this setting for my field but there is no way to do it at the moment

A temporary solution would be to extend ACF fields, but since this option is on a lots of field it is a bit problematic. Could we expose a methode addSetting() on Field so we can on the fly add arbitrary setting ?

**Comment by Grafikart** [comment]
I like the "with" it seems closer with the laravel way of doing things (and it implies the fluent API). I'm not sure about the function but it could accept 2 params or an array.

```php
->with('key', 'value');
->with(['key' => $value, 'key2' => $value2])
```

**Comment by vinkla** [comment]
The `withSettings` method has been merged and you may try it by using branch alias `13.2`.
