### ISSUE TITLE
Ordering Registration / Rendering of Groups for Taxonomies

### ISSUE THREAD

**Issue by mfs-bldmghty** [vinkla/extended-acf#117]
First, I haven't checked this with posts or users, etc. only taxonomies. 

I have a class. I have three methods, each for a different register_extended_field_group(). 

In my bootstrap class, I have 3 actions, something like:

```
 add_action( 'acf/init', array( $new_ext_acf, 'register_field_group_region_notification_emails' ), 300 );
 add_action( 'acf/init', array( $new_ext_acf, 'register_field_group_region_schedule_pickups' ), 100 );
 add_action( 'acf/init', array( $new_ext_acf, 'register_field_group_region_pickup_limits' ), 200 );
```
What's wonky is the actions' priorities aren't working. Regardless of those numbers, the 3 different groups are rendered in the same order. 

I even tried: 

`add_action( 'acf/init', array( $new_ext_acf, 'register_field_group_region_all' ), 300 );`

and then in that CB method putting the other methods in the order I needed. But that doesn't work either. The rendered order ignores the order in my code. 

Maybe it's not a bug? If not, how do I control the order the groups are rendered in?

**Comment by vinkla** [comment]
I'm closing this since it doesn't seem related to this package.

**Comment by mfs-bldmghty** [comment]
Wait. What? What's it related to then? If I'm using your package and can't get content rendered in the necessary order regardless of how I approach your package. That doesn't make sense to say it's got nothing to do with this package. There's nothing else involved and the package is being used as specified.

**Comment by vinkla** [comment]
I suggest you try asking this in the ACF forum.

**Comment by mfs-bldmghty** [comment]
I figure it out. I should have been using the  'menu_order' => arg.

Sorry about that. I didn't see that the first time.
