### ISSUE TITLE
OpenStreetMap creating custom fields

### ISSUE THREAD

**Issue by LeoGAUTRET** [vinkla/extended-acf#118]
Hi, i hope you're well. 

I have a question about how to create customs OpenStreetMap fields. I read and applied the doc but I still get an " Uncaught Error : Class "Extended\ACF\Fields\Field" not found "... I've been checking for several hours now, and every class is included as intended and explained on the doc. I guess I'm missing something, but I have no idea what.

This is not my first time creating custom OSM fields, but the previous times it worked perfectly. I've even tried copying and pasting, but it still doesn't work...

Could you maybe give me some help ?

**Comment by vinkla** [comment]
Make sure you've installed version 13 or later.

**Comment by LeoGAUTRET** [comment]
Yes my version is 13.2

**Comment by vinkla** [comment]
Then I don't know. I suggest asking in a forum.
