### ISSUE TITLE
Add ACF number field float support for min and max field properties

### ISSUE THREAD

**Issue by menno-ll** [vinkla/extended-acf#120]
I'm attempting to make a number field, however the number field does not support using floats as the `min` or `max` option.
It does however support this for the `step` option.

At this moment, creating a setup like this is therefore impossible:

```php
$field = Number::make( _x( 'Some label', 'Fields', 'some-textdomain' ), 'some-field-name' )
	->min( 0.5 ) // Impossible
	->max( 1.5 ) // Impossible
	->step( 0.1 )
	->defaultValue( 1.0 )
	->required();
```

**Comment by vinkla** [comment]
If you feel up for it, please submit a pull request changing the type hints from `int` to `float`.

**Comment by menno-ll** [comment]
Hi @vinkla 

Yes, i've created the [Pull request #121](https://github.com/vinkla/extended-acf/pull/121) for you and linked it to this Github Issue.

**Comment by vinkla** [comment]
Released in https://github.com/vinkla/extended-acf/releases/tag/13.2.1
