### ISSUE TITLE
Improve field creation with choices method by automatically converting values using `sanitize_title`

### ISSUE THREAD

**Issue by vinkla** [vinkla/extended-acf#124]
When I create fields with the choices method, the keys are usually identical to the values.

```php
ButtonGroup::make('Align')
    ->choices([
        'left' => 'Left',
        'center' => 'Center',
    ])
    ->defaultValue('left');
```

Rather than converting the values into keys manually, we can use `sanitize_title` to automatically transform them into snake_case, thus obtaining the same outcome.

```php
ButtonGroup::make('Align')
    ->choices(['Left', 'Center'])
    ->defaultValue('left');
```

We could go even further by allowing the array items to be passed as arguments to a function, making it even cleaner.

```php
ButtonGroup::make('Align')
    ->choices('Left', 'Center')
    ->defaultValue('left');
```

**Comment by nikrowell** [comment]
Hi @vinkla!

I haven't used **Extended ACF** on a project yet (keep that in mind with this comment 😉) but hoping to soon! Love the idea of programatic ACF fields and how this one is architected compared to others I've researched.

This is a clever idea, but I wonder if it's better to keep choices more explicit? It deviates from how ACF handles them when using the standard UI and could introduce breaking changes. For example, if someone had this:

```php
Select::make('View Mode')
    ->choices(['Map', 'Grid', 'List'])
    ->defaultValue('Map');
```
Would a line like `if (get_field('view_mode') === 'Map')` stop working if the field is now using `map` as the default?

**Comment by vinkla** [comment]
> This is a clever idea, but I wonder if it's better to keep choices more explicit? It deviates from how ACF handles them when using the standard UI and could introduce breaking changes. For example, if someone had this:

I agree that it would be beneficial to be clear and unambiguous. The example you provided will result in an array that is indexed.

```php
Select::make('View Mode')
    ->choices(['Map', 'Grid', 'List']); // [0 => 'Map', 1 => 'Grid', 2 => 'List']
```

I examined how the ACF UI handles this, and it appears that it simply returns the value without any formatting.

```php
Select::make('View Mode')
    ->choices(['Map', 'Grid', 'List']); // ['Map' => 'Map', 'Grid' => 'Grid', 'List' => 'List']
```

This is taken from the documentation:

> The choices displayed when selecting a value. Enter each choice on a new line (eg. Red). For more control over the value and label, you may use a colon to specify both (eg. ‘red : Red’).

I'd say we can whip up formatted values on the fly. It'll be beneficial for folks using this package.
