### ISSUE TITLE
Rename ReadOnly to Writable on 11.x tag

### ISSUE THREAD

**Issue by MaximVanhove** [vinkla/extended-acf#128]
Hello,

Thank you for your amazing work so far. We have a lot of websites running with this package. Many of them are running PHP 7.4 and need an update tot PHP 8. To make this possible we would need to have a version working on both PHP 7 and PHP 8.

I propose to create a 11.x branch where we can ship a minor version to support these. I have already a working branch, but I can not create a PR because there is no 11.x branch on this repo.

You can check it out here: https://github.com/MaximVanhove/extended-acf/commit/5c1aff4bf49dd3758220666e74d379f5d3a04b5a

**Comment by vinkla** [comment]
I'm glad you like the package. Unfortunately, we cannot release a new minor version on 11 with your suggested changes, as it would be a breaking change. This could potentially break a lot of projects using that version. What is preventing you from upgrading to a later version?

**Comment by vinkla** [comment]
No worries! If you have any other suggestions, don't hesitate to send them my way.
