### ISSUE TITLE
Strange issues when setting up languages with Polylang

### ISSUE THREAD

**Issue by mcamprecios** [vinkla/extended-acf#129]
Hello!

I'm finding some strange issues when translating my post contents with Polylang. Templates using Flexible Contents seem to work fine, but there is something wrong with Custom Post Types.

Primary language posts are fine. But secondary languages don't get the correct data. 

For example, secondary language post will get an image as an ID string, while the primary language gets the expected array. And for an a group field, the primary would work as expected, while the secondary gets an empty string.

I'm outputting the data in the template for testing, and both posts have the exact same content:

- http://coponsfortuny.marc-c.studio/en/events/41a-setmana-del-llibre-en-catala-4/ (primary language)
- http://coponsfortuny.marc-c.studio/es/events/41a-setmana-del-llibre-en-catala-3/ (secondary language)

They aren't set as each others translation. I simply set up their language. Hence, I believe they would just hold the same data.

Any ideas or solutions would be very welcome.

Massive thanks for your work!

**Comment by vinkla** [comment]
We can't debug your application for you, so please use a forum instead. If you discover a bug, submit a pull request.
