### ISSUE TITLE
some acf-extended-specific settings (`acfe_*`) have no effect

### ISSUE THREAD

**Issue by montchr** [vinkla/extended-acf#130]
ACF Extended adds some settings to existing fields (prefixed with `acfe_`). It seems that they have no effect when added to a field via the `withSettings()` methods. When configuring this setting in the ACF UI, I can confirm that it has the desired effect.

I saw #105 but it seems like I'm running into something else, as I'm running a current version of extended-acf.

The simplest example I found that doesn't require the premium version of that plugin is the ["Instruction Placement"](https://www.acf-extended.com/features/field-groups/instruction-placement) addition of a tooltip option to the `instruction_placement` field setting:

```php
Text::make('Title')
	->instructions('Write an instruction.')
    ->withSettings([
        'instruction_placement' => 'acfe_instructions_tooltip',
    ])
```

The issue isn't just localised to `instruction_placement`. I haven't been able to get the [Display Title](https://www.acf-extended.com/features/field-groups/display-title) setting working either (though it's possible I'm misunderstanding its intended usage):

```php
Text::make('Title')
    ->withSettings([
        'acfe_display_title' => 'Not a Title',
    ])
```

However, the issue doesn't affect all ACFE settings. The ["stylised button" setting](https://www.acf-extended.com/features/fields/repeater#stylised-button) added to Repeater works for me:

```php
Repeater::make('Items')
    ->instructions('Select up to three.')
    ->withSettings([
        'acfe_display_title' => 'The Items', // doesn't work
        'acfe_repeater_stylised_button' => 1, // works!
        'instruction_placement' => 'acfe_instructions_tooltip', // doesn't work
    ])
```

**Comment by vinkla** [comment]
What is the output when generating PHP from the dashboard using the same settings?
