### ISSUE TITLE
[Feature Request]: Export extended-acf fields from ACF dashboard

### ISSUE THREAD

**Issue by chrillep** [vinkla/extended-acf#133]
> The ACF PHP API has remained largely the same for the past decade, [as @Log1x stated](https://github.com/Log1x/acf-composer/issues/167#issuecomment-1574301562), and all of the related packages can be considered feature complete. However, there are some areas that I would like to improve in the `vinkla/extended-acf` package in the future:
> 
> * Introducing the ability to set custom keys, which could be beneficial when converting an exported PHP array from the ACF dashboard or when updating from an earlier version of the package (which I have done multiple times).
> * Adding a method for setting the column width of a field, instead of requiring width to be passed to the `wrapper` method.
> * Supporting the clone field, although I'm not sure this is necessary; I have never needed to use the field since I stopped registering fields from the dashboard.

perhaps add a feature to export to extended-acf from admin?
or 
cli command that does the conversion from array to classes

NOT a small feature tho :)

_Originally posted by @chrillep in https://github.com/vinkla/extended-acf/issues/126#issuecomment-1694331667_

**Comment by chrillep** [comment]
not sure how to test it tho.
Maybe we could use heredoc that we could parse and generate files from.
then test that the generated files work.

**Comment by chrillep** [comment]
it would help if acf would maintain a complete json schema.
* https://github.com/AdvancedCustomFields/acf/issues/834#issuecomment-1612563084

**Comment by vinkla** [comment]
This is a good idea, but I won't be working on it. If anyone wants to add this feature, please leave a comment. I will close this issue for now.
