### ISSUE TITLE
column() must be specified after wrapper()

### ISSUE THREAD

**Issue by kaelansmith** [vinkla/extended-acf#134]
@vinkla Love the new column() method. I noticed that if you specify column() followed by wrapper(), wrapper() will override column(); example:
```bash
Image::make('Logo')
  ->instructions('For use on light backgrounds')
  ->column(50),
Image::make('Logo on dark')
  ->instructions('For use on dark backgrounds')
  ->column(50)
  ->wrapper(['class' => 'dark-bg']),
```
In this case ^, the second Image field won't be 50%. The simple solution is to move column() after wrapper():
```bash
Image::make('Logo')
  ->instructions('For use on light backgrounds')
  ->column(50),
Image::make('Logo on dark')
  ->instructions('For use on dark backgrounds')
  ->wrapper(['class' => 'dark-bg'])
  ->column(50),
```
and I can confirm that in this case ^, the class of 'dark-bg' still gets applied. So this isn't really a bug, but perhaps you could add a note to the README?

**Comment by vinkla** [comment]
I'm glad you like it, Kaelan! 🙌 

If you're willing, please send a pull request to update the `column` section in the documentation.

**Comment by vinkla** [comment]
Another idea is to support merge the existing settings in the `wrapper` method. This is the way.

**Comment by vinkla** [comment]
Added in 13.7.1
