### ISSUE TITLE
Relationship field : PostStatus filter is missing

### ISSUE THREAD

**Issue by gturpin-dev** [vinkla/extended-acf#137]
Hi,

First of all, thanks for this awesome wrapper !
I've searched for the Relationship field and it seems to use Trait for filtering by PostType and by Taxonomies.
But in the ACF documentation for this field ( https://www.advancedcustomfields.com/resources/relationship/#settings Filter by Post Status ) It's also possible to filter by post status.
I don't find anything related to this feature in the Relationship class

Am I missing something ?

Thanks

**Comment by vinkla** [comment]
Thanks for your suggestion. Please submit a pull request with this feature and I'll take a look at it.

**Comment by gturpin-dev** [comment]
So, as I've mentionned in the PR,
I've added the PostStatus filter to the FilterBy trait because filtering by post_status is possible for multiple fields and not only the Relationship.

Maybe it's better to create a separate trait like FilterByPostStatus idk

I've tested with this code and it works propery, even if I replace with draft or other statuses :

```php
add_action('acf/init', function() {
    register_extended_field_group([
        'title' => 'About',
        'fields' => [
			Relationship::make( 'Related pages' )
					->postTypes( [ 'page' ] )
					->postStatus( [ 'publish' ] )
					->filters( [
						'search', 
						'taxonomy'
					] )
					->elements( ['featured_image'] )
					->min(0)
					->max(4)
					->returnFormat( 'id' )
        ],
        'location' => [
            Location::where('post_type', 'page')
        ],
    ]);
} );```
