### ISSUE TITLE
Meta Query for User Roles field

### ISSUE THREAD

**Issue by matbrady** [vinkla/extended-acf#140]
## Problem 

Unable to query posts by a meta value that's creating using a [User Roles field](https://www.acf-extended.com/features/fields/user-roles)

## Expected Result

Should be able to query posts based on the value of a User Roles custom field. Example query:
```
get_posts([
    'post_type' => $post_type,
    'posts_per_page' => -1,
    'status' => 'publish',
    'meta_query' => [
        [
            'key' => 'roles',
            'value' => ['administrator'],
            'compare' => 'IN'
        ]
    ]
]);
```

**Comment by vinkla** [comment]
I understand the confusion regarding similar names, but this project is not a part of ACF Extended.
