### ISSUE TITLE
add line to changelog of V14

### ISSUE THREAD

**Issue by menno-ll** [vinkla/extended-acf#148]
Since V14 of extended acf, a lot of changes have been made.
There is a change I've found that has not been documented in the changelog on the releases page of github.
I think the line below should be added to the changelog.

Renamed `message` method to `body`.

Could you please add that for the future developers looking to update?
Thanks :D.

**Comment by vinkla** [comment]
It is documented.

**Comment by menno-ll** [comment]
I think you are pointing to the documentation itself.
But it seems to not be present in the changelog at https://github.com/vinkla/extended-acf/releases/.
Or am I missing something?

**Comment by vinkla** [comment]
Fixed in 34cc074d24493130e55694f9f2da9d976f79f5c6
